name = "discordbot"
main = "src/server.js"
compatibility_date = "2024-01-01"

[vars]
# Add non-secret variables here
DISCORD_APP_ID = "1226374898289741914" 

# Secrets should be added via 'wrangler secret put NAME' or in a .dev.vars file for local development
# Required secrets:
# DISCORD_TOKEN
# DISCORD_PUBLIC_KEY
# GROQ_API_KEY
# ASK_CHANNEL_ID
# REPORT_CHANNEL_ID
# STAFF_ROLE_ID
